spring:
  datasource:
    username: postgres
    password: fenix000
    url: jdbc:postgresql://localhost:5432/spring_batch
    dbcp2:
      driver-class-name: org.postgresql.Driver
        
  batch:
    jdbc:
      initialize-schema: ALWAYS
